import dotenv from 'dotenv';

dotenv.config();

export const envVariables = {
  WALLET_CONNECT_PROJECT_ID: process.env.WALLET_CONNECT_PROJECT_ID,
  GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID,
  GOOGLE_CLIENT: process.env.GOOGLE_CLIENT,
  GOOGLE_AUTH_URI: process.env.GOOGLE_AUTH_URI,
  GOOGLE_TOKEN_URI: process.env.GOOGLE_TOKEN_URI,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_AUTH_PRIVODER_CERT_URL: process.env.GOOGLE_AUTH_PRIVODER_CERT_URL,
  GOOGLE_REDIRECT_URL: process.env.GOOGLE_REDIRECT_URL,
  GOOGLE_JAVASCRIPT_ORIGIN: process.env.GOOGLE_JAVASCRIPT_ORIGIN,
  PAYPAL_BASE_URL: process.env.PAYPAL_BASE_URL,
  PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
  PAYPAL_CLIENT_SECRET: process.env.PAYPAL_CLIENT_SECRET,
};